# Generated by Django 5.2 on 2025-04-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMatricula', '0002_asignatura_programa_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nivel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
