# Generated by Django 5.2 on 2025-04-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionMatricula', '0003_usuarios_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='identificacion',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionMatricula.programa'),
        ),
    ]
